try:
    print("In try block")
except Exception as e:
    print(e)
finally:
    print("In finally block") 